'use strict';
const $=id=>document.getElementById(id), M=ScanModel;
let sample=M.surface(), points=[],results=[],cursor=0,running=false,angle=-0.7,tilt=0.65,zoom=1,credit=0,last=0;
let config={},drag=null;
function setup(){running=false;cursor=0;results=[];credit=0;config={radius:+$('radius').value,gap:+$('gap').value,resolution:+$('resolution').value,mode:$('mode').value,dwell_s:0.02,flyback_s:0.1};points=M.path(sample,config.resolution,config.mode==='snake');$('start').textContent='开始扫描';$('rv').textContent=config.radius.toFixed(1)+' nm';$('gv').textContent=config.gap.toFixed(1)+' nm';$('status').textContent=sample.atomCount?`已导入 ${sample.atomCount.toLocaleString()} 个原子；显示离散上表面，空网格不填补。`:'样品就绪，可开始扫描。';render();}
function canvas(id){const c=$(id),d=devicePixelRatio||1,w=c.clientWidth,h=c.clientHeight;if(c.width!==Math.round(w*d)||c.height!==Math.round(h*d)){c.width=Math.round(w*d);c.height=Math.round(h*d);}const ctx=c.getContext('2d');ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,w,h);return {ctx,w,h};}
function project(x,y,z,w,h){x-=sample.width/2;y-=sample.depth/2;const u=x*Math.cos(angle)-y*Math.sin(angle),v=x*Math.sin(angle)+y*Math.cos(angle),s=Math.min(w,h)*0.62/Math.max(sample.width,sample.depth)*zoom;return [w/2+u*s,h*0.65+(v*Math.sin(tilt)-z*Math.cos(tilt))*s,v*Math.cos(tilt)+z*Math.sin(tilt)];}
function color(z){const t=Math.max(0,Math.min(1,z/(maxHeight()||1)));return `rgb(${30+55*t},${85+140*t},${110+115*t})`;}
function maxHeight(){return sample.h.reduce((a,b)=>Number.isFinite(b)?Math.max(a,b):a,0);}
function scene(){const {ctx,w,h}=canvas('scene'),p=(x,y,z)=>project(x,y,z,w,h),n=sample.n,dx=sample.width/(n-1),dy=sample.depth/(n-1),faces=[];
 for(let j=0;j<n-1;j++)for(let i=0;i<n-1;i++){const ids=[j*n+i,j*n+i+1,(j+1)*n+i+1,(j+1)*n+i];if(!ids.every(k=>sample.valid[k]))continue;const v=ids.map(k=>p(k%n*dx,Math.floor(k/n)*dy,sample.h[k]));faces.push({v,z:ids.reduce((a,k)=>a+sample.h[k],0)/4,depth:v.reduce((a,q)=>a+q[2],0)/4});}
 faces.sort((a,b)=>a.depth-b.depth);const top=maxHeight()||1;
 for(const f of faces){ctx.beginPath();f.v.forEach((v,i)=>i?ctx.lineTo(v[0],v[1]):ctx.moveTo(v[0],v[1]));ctx.closePath();const t=f.z/top;ctx.fillStyle=`rgb(${30+55*t},${85+140*t},${110+115*t})`;ctx.fill();}
 // Sparse imported samples are visible as occupied surface nodes.
 if(faces.length<(n*n)/4){ctx.fillStyle='#52c8d2';for(let k=0;k<n*n;k++)if(sample.valid[k]){const a=p(k%n*dx,Math.floor(k/n)*dy,sample.h[k]);ctx.fillRect(a[0]-1,a[1]-1,2,2);}}
 ctx.strokeStyle='#edf5ff99';ctx.lineWidth=1;ctx.beginPath();let connected=false,prev=null;for(const r of results){if(!Number.isFinite(r.z)){connected=false;continue;}const a=p(r.x,r.y,r.z);if(!connected||(config.mode==='raster'&&prev&&prev.j!==r.j))ctx.moveTo(a[0],a[1]);else ctx.lineTo(a[0],a[1]);connected=true;prev=r;}ctx.stroke();
 const r=results.length?results[results.length-1]:{...points[0],z:M.tipHeight(sample,points[0].x,points[0].y,config.radius,config.gap)};
 if(Number.isFinite(r.z)){const center=p(r.x,r.y,r.z+config.radius),apex=p(r.x,r.y,r.z),s=Math.min(w,h)*0.62/Math.max(sample.width,sample.depth)*zoom,R=config.radius*s;
 ctx.strokeStyle='#f4c66d';ctx.setLineDash([4,4]);const ground=p(r.x,r.y,0);ctx.beginPath();ctx.moveTo(apex[0],apex[1]);ctx.lineTo(ground[0],ground[1]);ctx.stroke();ctx.setLineDash([]);
 const shaft=p(r.x,r.y,r.z+config.radius+Math.max(sample.width,sample.depth)*0.18);ctx.strokeStyle='#8594ad';ctx.lineWidth=Math.max(4,R*.65);ctx.beginPath();ctx.moveTo(center[0],center[1]);ctx.lineTo(shaft[0],shaft[1]);ctx.stroke();
 const grad=ctx.createRadialGradient(center[0]-R*.3,center[1]-R*.3,R*.1,center[0],center[1],R);grad.addColorStop(0,'#fff3be');grad.addColorStop(1,'#b17a21');ctx.fillStyle=grad;ctx.beginPath();ctx.arc(center[0],center[1],R,0,Math.PI*2);ctx.fill();
 }
 ctx.lineWidth=1.5;for(const [end,label,c]of [[[sample.width,0,0],'X','#ff8c8c'],[[0,sample.depth,0],'Y','#82dfb1'],[[0,0,Math.max(4,top)],'Z','#9abaff']]){const a=p(0,0,0),b=p(...end);ctx.strokeStyle=c;ctx.fillStyle=c;ctx.beginPath();ctx.moveTo(a[0],a[1]);ctx.lineTo(b[0],b[1]);ctx.stroke();ctx.fillText(label+' (nm)',b[0]+4,b[1]);}
}
function map(){const {ctx,w,h}=canvas('map'),N=config.resolution,s=Math.min(w-65,h-25)/N,ox=38,oy=8;ctx.fillStyle='#223044';ctx.fillRect(ox,oy,N*s,N*s);for(const r of results)if(Number.isFinite(r.z)){ctx.fillStyle=color(r.z-config.gap);ctx.fillRect(ox+r.i*s,oy+(N-1-r.j)*s,Math.ceil(s),Math.ceil(s));}ctx.fillStyle='#afc4dc';ctx.fillText('0',ox,oy+N*s+15);ctx.fillText(sample.width.toFixed(1)+' nm → X',ox+N*s*.55,oy+N*s+15);ctx.fillText('Y ↑',3,20);}
function profile(){const {ctx,w,h}=canvas('profile'),row=results.length?results[results.length-1].j:0,rs=results.filter(r=>r.j===row),max=Math.max(maxHeight()+config.gap+config.radius,1);ctx.strokeStyle='#344963';ctx.beginPath();ctx.moveTo(30,10);ctx.lineTo(30,h-25);ctx.lineTo(w-10,h-25);ctx.stroke();for(const [key,c]of [['surface','#56d8cd'],['z','#f0c66c']]){ctx.strokeStyle=c;ctx.beginPath();let active=false;for(const r of rs){if(!Number.isFinite(r[key])){active=false;continue;}const x=30+r.x/sample.width*(w-45),y=h-25-r[key]/max*(h-40);if(active)ctx.lineTo(x,y);else ctx.moveTo(x,y);active=true;}ctx.stroke();}ctx.fillStyle='#acc1d8';ctx.fillText('z (nm)',5,10);ctx.fillText('x (nm)',w-55,h-5);ctx.fillText('行 '+(row+1),w-65,15);}
function render(){scene();map();profile();$('progress').value=cursor/points.length;$('count').textContent=`采样：${cursor} / ${points.length}`;const r=results.at(-1);$('position').textContent=r?`x ${r.x.toFixed(2)} · y ${r.y.toFixed(2)} · z ${Number.isFinite(r.z)?r.z.toFixed(2):'无覆盖'} nm`:'位置：待扫描';$('time').textContent=`仿真时间：${r?r.time_s.toFixed(2):'0.00'} s`;}
function tick(t){const dt=Math.min((t-last)/1000,0.1);last=t;if(running){credit+=dt*(+$('speed').value);while(credit>=1&&cursor<points.length){const p=points[cursor],z=M.tipHeight(sample,p.x,p.y,config.radius,config.gap);results.push({...p,z,surface:M.height(sample,p.x,p.y),time_s:cursor*config.dwell_s+(config.mode==='raster'?p.j*config.flyback_s:0)});cursor++;credit--;}if(cursor===points.length){running=false;$('start').textContent='重新扫描';$('status').textContent='扫描完成。可以旋转查看或导出完整数据。';}render();}requestAnimationFrame(tick);}
$('start').onclick=()=>{if(cursor===points.length)setup();running=!running;$('start').textContent=running?'暂停':'继续';};$('reset').onclick=setup;
for(const id of ['radius','gap','resolution','mode'])$(id).onchange=setup;
$('sample').onchange=()=>{sample=M.surface($('sample').value);setup();};$('speed').oninput=()=>{$('sv').textContent=$('speed').value+' 点/秒';};$('speed').oninput();
$('import').onclick=()=>$('file').click();$('file').onchange=async()=>{const f=$('file').files[0];if(!f)return;running=false;$('start').textContent='继续';try{const ext=f.name.split('.').pop().toLowerCase();if(!['pdb','xyz'].includes(ext))throw Error('请选择 PDB 或 XYZ');sample=M.fromAtoms(M.parseAtoms(await f.text(),ext,$('unit').value));sample.source=f.name;setup();}catch(e){$('status').textContent='导入失败：'+e.message;}$('file').value='';};
$('camera').onclick=()=>{angle=-.7;tilt=.65;zoom=1;render();};$('scene').onpointerdown=e=>{drag=[e.clientX,e.clientY];$('scene').setPointerCapture(e.pointerId);};$('scene').onpointermove=e=>{if(!drag)return;angle+=(e.clientX-drag[0])*.008;tilt=Math.max(.15,Math.min(1.35,tilt+(e.clientY-drag[1])*.006));drag=[e.clientX,e.clientY];render();};$('scene').onpointerup=()=>drag=null;$('scene').onpointercancel=()=>drag=null;$('scene').onwheel=e=>{e.preventDefault();zoom=Math.max(.4,Math.min(3,zoom*Math.exp(-e.deltaY*.001)));render();};
$('export').onclick=()=>{const data={version:1,units:'nm',model:'discrete spherical tip envelope; ideal tracking; g = vertical lift',config,sample,results,completed:cursor===points.length};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='tddemo-scan.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
window.addEventListener('resize',render);setup();requestAnimationFrame(tick);
